image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test
  - build

maven-test:
  image: maven:3.6.2-jdk-8-openj9
  stage: test
  script: "mvn install"

docker-build:
  stage: build
  script:
  - docker build . -f docker/Dockerfile -t robert_richter/docker-demo
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD hub.docker.com
  - docker push robert_richter/docker-demo