# for docker
sudo: required
services:
  - docker

language: java
jdk: openjdk8

# test code including code coverage
before_install:
  - mvn verify

# build docker image 
script:
  - docker build . -f docker/Dockerfile -t robertrichter/docker-demo
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD hub.docker.com
  - docker push robertrichter/docker-demo

