apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spring-app
  template:
    metadata:
      labels:
        component: spring-app
    spec:
      volumes:
        - name: logging-config
          configMap:
            name: log4j2-config-map
            items:
            - key: log4j2.xml
              path: log4j2.xml
      containers:
        - name: spring-app
          image: robertrichter/docker-demo:v1
          ports:
            - containerPort: 9091
          volumeMounts:
            - mountPath: /app/config/
              name: logging-config
          env: 
            - name: POSTGRES_HOSTNAME
              value: postgres-cluster-ip-service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_PORT
              value: '5432'