apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-config-map
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration>
      <Appenders>
        <Console name="Console" target="SYSTEM_OUT">
                <PatternLayout  pattern="%d | %p | %C{1.} [%t] %m%n" />
        </Console>
    </Appenders>
    <Loggers>
        <Root level="INFO">
            <AppenderRef ref="Console" />
        </Root>
    </Loggers>
    </Configuration>